CREATE TABLE RECOMMENDED_SR
(
  RSRID INT NOT NULL,
  CPU VARCHAR(200) NOT NULL,
  GPU VARCHAR(200) NOT NULL,
  RAM VARCHAR(20) NOT NULL,
  Storage VARCHAR(10) NOT NULL,
  StorageType VARCHAR(10) NOT NULL,
  AdditionalNotes VARCHAR(1000) NOT NULL,
  OS VARCHAR(100) NOT NULL,
  PRIMARY KEY (RSRID)
);

CREATE TABLE GENRE_TAG
(
  TagID INT NOT NULL,
  TagName VARCHAR(150) NOT NULL,
  PRIMARY KEY (TagID)
);

CREATE TABLE PUBLISHER
(
  PublisherID INT NOT NULL,
  PublisherName VARCHAR(300) NOT NULL,
  YearFounded DATE NOT NULL,
  Description VARCHAR(1000) NOT NULL,
  Country VARCHAR(200) NOT NULL,
  PRIMARY KEY (PublisherID)
);

CREATE TABLE DEVELOPER
(
  DeveloperID INT NOT NULL,
  DeveloperName VARCHAR(300) NOT NULL,
  YearFounded DATE NOT NULL,
  Description VARCHAR(1000) NOT NULL,
  Country VARCHAR(100) NOT NULL,
  PublisherID INT NOT NULL,
  PRIMARY KEY (DeveloperID),
  FOREIGN KEY (PublisherID) REFERENCES PUBLISHER(PublisherID)
);

CREATE TABLE SALE_EVENT
(
  SaleID INT NOT NULL,
  SaleStartDate INT NOT NULL,
  SaleEndDate INT NOT NULL,
  DiscountPercentage INT NOT NULL,
  PublisherID INT NOT NULL,
  PRIMARY KEY (SaleID),
  FOREIGN KEY (PublisherID) REFERENCES PUBLISHER(PublisherID)
);

CREATE TABLE GAME
(
  GameID INT NOT NULL,
  GameName VARCHAR(300) NOT NULL,
  Price FLOAT NOT NULL,
  AgeRating VARCHAR(25) NOT NULL,
  AverageRating FLOAT NOT NULL,
  Description VARCHAR(1000) NOT NULL,
  ReleaseDate DATE NOT NULL,
  RSRID INT NOT NULL,
  PublisherID INT NOT NULL,
  DeveloperID INT NOT NULL,
  PRIMARY KEY (GameID),
  FOREIGN KEY (RSRID) REFERENCES RECOMMENDED_SR(RSRID),
  FOREIGN KEY (PublisherID) REFERENCES PUBLISHER(PublisherID),
  FOREIGN KEY (DeveloperID) REFERENCES DEVELOPER(DeveloperID)
);

CREATE TABLE PLATFORM
(
  PlatformID INT NOT NULL,
  GameID INT NOT NULL,
  PRIMARY KEY (PlatformID, GameID),
  FOREIGN KEY (GameID) REFERENCES GAME(GameID)
);

CREATE TABLE MINIMUM_SR
(
  CPU VARCHAR(200) NOT NULL,
  GPU VARCHAR(200) NOT NULL,
  RAM VARCHAR(20) NOT NULL,
  Storage VARCHAR(10) NOT NULL,
  StorageType VARCHAR(10) NOT NULL,
  AddtionalNotes VARCHAR(1000) NOT NULL,
  OS VARCHAR(100) NOT NULL,
  GameID INT NOT NULL,
  PRIMARY KEY (GameID),
  FOREIGN KEY (GameID) REFERENCES GAME(GameID)
);

CREATE TABLE TAG_ASSOCIATION
(
  GameID INT NOT NULL,
  TagID INT NOT NULL,
  PRIMARY KEY (GameID, TagID),
  FOREIGN KEY (GameID) REFERENCES GAME(GameID),
  FOREIGN KEY (TagID) REFERENCES GENRE_TAG(TagID)
);

CREATE TABLE DEVELOPED
(
  DeveloperID INT NOT NULL,
  GameID INT NOT NULL,
  PRIMARY KEY (DeveloperID, GameID),
  FOREIGN KEY (DeveloperID) REFERENCES DEVELOPER(DeveloperID),
  FOREIGN KEY (GameID) REFERENCES GAME(GameID)
);

CREATE TABLE SALE_INCLUDES
(
  GameID INT NOT NULL,
  SaleID INT NOT NULL,
  PRIMARY KEY (GameID, SaleID),
  FOREIGN KEY (GameID) REFERENCES GAME(GameID),
  FOREIGN KEY (SaleID) REFERENCES SALE_EVENT(SaleID)
);